# Clustering con K-Means

In [1]:
import numpy as np

In [2]:
data= np.random.random(90).reshape(30, 3)
data

array([[2.95222283e-01, 6.36324918e-01, 3.90552745e-01],
       [5.37064035e-01, 3.83419723e-01, 2.47113733e-01],
       [8.55804383e-01, 6.75284981e-01, 1.83443627e-01],
       [9.05258693e-01, 3.53983687e-01, 1.28025398e-02],
       [4.77348933e-01, 5.45577126e-01, 4.65381299e-01],
       [5.22561826e-01, 8.18764293e-01, 2.35109546e-01],
       [9.42863330e-01, 6.72865281e-02, 5.24023100e-01],
       [3.57651277e-01, 6.25076892e-01, 5.36570157e-01],
       [3.73206799e-02, 3.64087300e-02, 7.07541001e-01],
       [1.05239520e-01, 1.61766983e-01, 4.53452642e-01],
       [5.09377944e-02, 5.90382692e-01, 1.07025934e-01],
       [5.52575246e-01, 8.50635711e-01, 9.37338171e-01],
       [5.14058344e-01, 5.54816851e-01, 3.33404673e-01],
       [4.93843459e-01, 2.53303101e-02, 5.84814439e-02],
       [5.95993948e-01, 9.01134844e-01, 7.07234452e-01],
       [8.63175180e-01, 1.60701086e-01, 9.18424102e-02],
       [5.37173093e-01, 1.26303909e-01, 8.75921103e-01],
       [3.65655366e-01, 8.03226

In [3]:
c1= np.random.choice(range(len(data)))
c2= np.random.choice(range(len(data)))
clust_centers= np.vstack([data[c1], data[c2]])
clust_centers

array([[0.86317518, 0.16070109, 0.09184241],
       [0.87645895, 0.71605224, 0.94524293]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
vq(data, clust_centers)

(array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 0]),
 array([0.79875928, 0.42433625, 0.52272526, 0.21301757, 0.64700677,
        0.75471194, 0.44928458, 0.66667185, 1.03757843, 0.83977947,
        0.91901381, 0.35082168, 0.57927725, 0.39477097, 0.41178177,
        0.        , 0.68390314, 0.56908679, 0.74485243, 1.1349463 ,
        0.78520586, 0.44151181, 0.55065536, 0.87863622, 0.29166653,
        0.        , 0.87037817, 0.37299135, 0.74113439, 0.86285709]))

In [6]:
from scipy.cluster.vq import kmeans

In [8]:
kmeans(data, clust_centers)
#Los centros de los clusters. El último valor es la suma de los cuadrados de los errores normalizada.

(array([[0.43159554, 0.4024501 , 0.28017985],
        [0.47905946, 0.56621512, 0.79349946]]),
 0.4019145899980771)

In [9]:
#Si en lugar de darle los centroides le damos el número de clusters= 2 obtenemos un resultado similar
kmeans(data, 2)

(array([[0.33909202, 0.54439386, 0.55956705],
        [0.70017479, 0.25320913, 0.19863151]]),
 0.38539887812041473)