# Regresión lineal con scykit-learn

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

In [3]:
fullpath= "../../Datasets/ads/Advertising.csv"

data= pd.read_csv(fullpath)

In [4]:
feature_cols= ["TV", "Radio", "Newspaper"]

In [5]:
x= data[feature_cols]
y= data["Sales"]

In [7]:
estimator= SVR(kernel= "linear")
selector= RFE(estimator, 2, step= 1)
selector= selector.fit(x, y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [8]:
selector.support_

array([ True,  True, False])

In [9]:
selector.ranking_

array([1, 1, 2])

In [11]:
x_pred= x[["TV", "Radio"]]

In [12]:
lm= LinearRegression()
lm.fit(x_pred, y)

LinearRegression()

In [13]:
lm.intercept_

2.9210999124051362

In [14]:
lm.coef_

array([0.04575482, 0.18799423])

In [15]:
lm.score(x_pred, y)

0.8971942610828956